stages:
  - build
  - test

build_centos7:
  stage: build
  script:
    - export CC=clang
    - export CXX=clang++
    - scripts/build_linux.sh
  artifacts:
    paths:
    - build/
    - ospray/
  tags:
    - centos7
  allow_failure: false

test_centos7:
  stage: test
  script:
    - scripts/test_linux.sh
  dependencies:
    - build_centos7
  tags:
    - centos7
